##################################################
#
# Compose-File for start up payara-4-full
# application server with database connection pool,
# using a postgresql conainer with postgres
# default image from dockerhub.
#
##################################################

version: "2"

services:

    billing-postgres-for-payara:
        image: postgres:9.6
        container_name: billing-postgres-for-payara
        environment:
            - POSTGRES_USER=devobst_billing
            - POSTGRES_PASSWORD=devobst_billing
        networks:
            - net
        ports:
            - "5433:5432"
        volumes:
            - postgres_data_billing:/var/lib/postgresql/data

    devobst-billing:
        image: hackathon-ubuntu-16.04-java-8-jdk-payara-4.1.1-app-billing
        container_name: billing-app-on-payara
        environment:
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=password
            - DB_USER=devobst_billing
            - DB_PASSWORD=devobst_billing
            - DB_SERVER_NAME=billing-postgres-for-payara
            - DB_PORT=5432
            - DB_NAME=devobst_billing
            - CONNECTION_POOLNAME=devobst_billing
        networks:
            - net
        ports:
            - "8080:8080"
            - "4848:4848"
        depends_on:
            - billing-postgres-for-payara

networks:
    net:

volumes:
    postgres_data_billing:
